[auth]
redirect_uri="https://vixis-1-nzm9.onrender.com/oauth2callback"
cookie_secret="437e5rgu454387y273yr78u2q836^%$%$#164537458585885u894589b8y8965657y09ki"
client_id="ea0e58b4-06e8-4cb6-bdcc-6be04bec7f6a"
client_secret="vkz8Q~9uXStHT-GmCZouRLLQUeaQYnEcHjg3vbmZ"
server_metadata_url="https://login.microsoftonline.com/6a89bdfa-85b1-42c0-b827-15b3fe8415da/v2.0/.well-known/openid-configuration"
